### ISSUE TITLE
C5.1 Controller Support

### ISSUE THREAD

**Issue by killtux** [ksvan/node-red-contrib-komfovent#26]
Hey there!

Any chance to get the other (the C5) controller supported too? I think the webinterface is pretty the same. But there are other modes (Comfort 1, Comfort 2, Economy 1, Economy 2 & Special).

I have an C5 installed and running. If you need access for testing - this would be no problem.

**Comment by ksvan** [comment]
A bit hard to make time for that unfortunately, depends on how big the difference really is on those controllers. Have you tested the nodes? does anything work, especially around setting modes is interesting?

**Comment by ksvan** [comment]
no reply, closing

**Comment by killtux** [comment]
sorry for the late reply. i tried to get it running but failed. is there any way to contact you directly?
